baseURL = "https://churchofturing.org/"
languageCode = "en-us"
title = "church_of_turing"
theme = "minimal"
publishDir= "../docs"


[params]
    author = "Alonzo Alan Emil Kurt"
    description = "Göd-el level Posts on Computation"
    accent = "blue"
    showBorder = false
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"

[[menu.icon]]
    url = "https://twitter.com/churchofturing/"
    name = "twitter"
    weight = 1


